### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by vatsim-me** [Axiacore/cachet-uptime-robot#10]
I've followed the readme and set up the monitor, however, we're seeing this error when running the app. Any ideas?
![error](https://cloud.githubusercontent.com/assets/9834698/18938535/29e0570a-85c7-11e6-9738-7d0a4120c075.PNG)

**Comment by camilonova** [comment]
Check you API keys

**Comment by ghost** [comment]
I got same issue I double checked all api keys
