### ISSUE TITLE
Won't work with Python 2.7 / 3.4 / 3.5.2

### ISSUE THREAD

**Issue by nixmomo** [Axiacore/cachet-uptime-robot#12]
If i run 
python3 update_status.py config.ini

the Script dont give a output and dont update my metrics.

if i run 
python update_status.py config.ini
i have a output

Traceback (most recent call last):
  File "update_status.py", line 5, in <module>
    import configparser
ImportError: No module named configparser

Config looks so
[uptimeRobot]
UptimeRobotMainApiKey = uabs323

[https://stats.uptimerobot.com/6DJHAUNxc/72222222]
CachetApiKey = XXXXxx2XXXX
CachetUrl = https://cachet-frntpage-url
MetricId = 2
ComponentId = 2

**Comment by camilonova** [comment]
Are you using Python 3.5?

**Comment by nixmomo** [comment]
No I use 3.4

Von meinem iPhone gesendet

**Comment by nixmomo** [comment]
No Ideas whats going wrong??

**Comment by camilonova** [comment]
I would recommend you to use Python 3.5

Thats why you get the import error.

**Comment by nixmomo** [comment]
Still the same with 3.5.2!
`root@server2:/home/cachet/cachet-uptime-robot# python3.5 -V
Python 3.5.2
root@server2:/home/cachet/cachet-uptime-robot# python3.5 update_status.py config.ini
root@server2:/home/cachet/cachet-uptime-robot#
`
