### ISSUE TITLE
Load balanced servers

### ISSUE THREAD

**Issue by shaun-ba** [Axiacore/cachet-uptime-robot#14]
What is the correct way to set up the configs/monitors here for load balanced servers? So say i want to create a single metric that uses the max from multiple monitors, is that possible?

If i have say 4 servers, 1 goes down, the uptime isn't effected so it would be false to show this monitor's stats. 

Hope i made my point clear!

**Comment by camilonova** [comment]
Currently is not supported, but feel free to work on this feature, send a PR and we can integrate it.
