### ISSUE TITLE
downgraded to python 2.7

### ISSUE THREAD

**Issue by fsoyer** [Axiacore/cachet-uptime-robot#18]
Hi Axiacore,
not really an issue but:
working on Centos7 servers, providing only python 2.7 that I don't want to change for now, I've downgraded your script to work with 2.7. Interested to propose it as an alternative or something else ?
Thanks for job,
Frank.

**Comment by williamsdb** [comment]
Hi Frank, can you publish your code changes as I'm in a situation like you where I can only use Python 2.7.

Thanks

**Comment by fsoyer** [comment]
Hi,
I just push it to Github https://github.com/fgth/cachet-uptime-robot-py27
'Hope that Axiacore will agree, please don't hesitate to tell if not.

**Comment by camilonova** [comment]
Is good to know there is a fork supporting this. Thank you.
