### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xe3' in position 36: ordinal not in range(128)

### ISSUE THREAD

**Issue by ElJoelReis** [Axiacore/cachet-uptime-robot#22]
Hello,
after add 3 monitors appears the error:

> Traceback (most recent call last):
  File "/root/cachet-uptime-robot/update_status.py", line 252, in <module>
    MONITOR.update()
  File "/root/cachet-uptime-robot/update_status.py", line 219, in update
    monitor['id'],
UnicodeEncodeError: 'ascii' codec can't encode character '\xe3' in position 36: ordinal not in range(128)

**Comment by camilonova** [comment]
Are you sure you are using python3 ?
