### ISSUE TITLE
ERROR: monitor is not valid

### ISSUE THREAD

**Issue by FleuryK** [Axiacore/cachet-uptime-robot#23]
Hello.

First of all, congratulations for your project and your work you have done.

Since yesterday, when I type the command "python3.5 update_status.py config.ini" I have this error: "ERROR: monitor is not valid" and impossible to go further as it stops.

My UptimeRobot API key and correct and my Cachet API key and correct also.

For now, I'm stuck by this error. Where is the problem ?

**Comment by camilonova** [comment]
Make sure you have the same url you are monitoring in the config file.
