### ISSUE TITLE
Triggers component change every check

### ISSUE THREAD

**Issue by daza111** [Axiacore/cachet-uptime-robot#24]
Hi there,

Everytime the script runs (*/5) it updates the status of the component to Operational, which triggers an email alert to subscribers. Is there anyway to avoid that?

Essentially, I want to check the uptimerobot status and if down change to down and trigger the email then. Each time is OK I don't need to know....

**Comment by camilonova** [comment]
I don't know how to do that, if you find a way feel free to send a PR or update this issue. Thanks.
