### ISSUE TITLE
Clarification about the README

### ISSUE THREAD

**Issue by 1stposition-ad** [Axiacore/cachet-uptime-robot#25]
Hello,

I have troubles understanding what i am supposed to fill in for following line: 
"[https://url.in.uptime.robot.com]: This exact "monitor" url set in UptimeRobot (eg. http://mywebsite.com)"
Is this url supposed to be the public status page provided by uptime robot?

**Comment by camilonova** [comment]
No, that should be the URL of the website you are monitoring
