### ISSUE TITLE
Config parse error

### ISSUE THREAD

**Issue by KeiroD** [Axiacore/cachet-uptime-robot#29]
Hi,

Just recently added this to my install and I'm getting the following error:

```
root@emberberry:/var/www/cachet-uptime-robot# python3 update_status.py
Traceback (most recent call last):
  File "update_status.py", line 228, in <module>
    CONFIG.read(sys.argv[1])
IndexError: list index out of range
```

Content of `config.ini` has been set up as follows:

```
root@emberberry:/var/www/cachet-uptime-robot# cat config.ini
[uptimeRobot]
UptimeRobotMainApiKey = [...]

[https://stats.uptimerobot.com/JqrBwiB2Y]
CachetApiKey = [..]
CachetUrl = https://status.heimkoma.com
MetricId = 1
ComponentId = 1
```

Obviously the API keys have been obscured. Perhaps you should show screenshots of how you got the config working, including the metrics and components?

Edit:

PEBCAK. I forgot to add `config.ini` to the command. However, when doing this:

```
root@emberberry:/var/www/cachet-uptime-robot# python3 update_status.py config.ini
root@emberberry:/var/www/cachet-uptime-robot#
```

No output is provided. Is this normal?

**Comment by ghost** [comment]
`[https://stats.uptimerobot.com/JqrBwiB2Y]`

You need to add the monitor url like https://domain.tld

**Comment by KeiroD** [comment]
>You need to add the monitor url like https://domain.tld

Tried that. Still no output. Is there a debug string that I can use to force it to output what it's doing?

**Comment by JonTheWong** [comment]
That error is generally due to the fact that your config is wrong.
Remove all example and just add your Uptime Robot monitor ID's

```
[uptimeRobot]
UptimeRobotMainApiKey = u2XXX40-ddd44df3XXXX6322157cc95e

[cachet]
CachetApiKey = XXXXXXXX
CachetUrl = https://status.domain.tld

[77868XXXX]
ComponentId = 1

[77868XXXX]
ComponentId = 2

[77868XXXX]
ComponentId = 4

[77868XXXX]
ComponentId = 5

[78134XXXX]
Componentid = 6
```
