### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by ElJoelReis** [Axiacore/cachet-uptime-robot#31]
Hello, from ID 1 to 9 the script works but from 10 onwards the following error appears:

> Traceback (most recent call last):
>   File "/home/XXX/web/XXX/public_html/cachet-uptime-robot/update_status.py", line 252, in <module>
>     MONITOR.update()
>   File "/home/XXX/web/XXX/public_html/cachet-uptime-robot/update_status.py", line 219, in update
>     monitor['id'],
> UnicodeEncodeError: 'ascii' codec can't encode character '\xed' in position 47: ordinal not in range(128)

My config is:

> [http://dominios.waxhost.pt/]
> CachetApiKey = API
> CachetUrl = URL
> MetricId = 11
> ComponentId = 11

**Comment by camilonova** [comment]
Which python version are you using?

**Comment by ElJoelReis** [comment]
Python 3.4.2

**Comment by ElJoelReis** [comment]
I closed the topic unintentionally

**Comment by ElJoelReis** [comment]
hello?

**Comment by camilonova** [comment]
UnicodeEncodeError are usually related to Python 2.7 use, can you try running the command using Python3.6 ?
