### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'uptimeRobotMonitorID1'

### ISSUE THREAD

**Issue by mnucci** [Axiacore/cachet-uptime-robot#33]
I am getting this error.  Here is my config.ini (private data changed)

```[uptimeRobot] // Global uptimerobot API
UptimeRobotMainApiKey = xxx

[cachet] // Global cachet status API
CachetApiKey = xxx
CachetUrl = http://status.mysite.com

[uptimeRobotMonitorID1] // This will update ComponentId 1 on the global Cachet
ComponentId = 1

[uptimeRobotMonitorID2] // Still possible to use custom cachet settings
CachetApiKey = xxxx
CachetUrl = http://status.mysite.com
MetricId = 1
ComponentId = 1 
```

This is what I get when I run it

```
$ python3 update_status.py config.ini --printIds
Traceback (most recent call last):
  File "update_status.py", line 398, in <module>
    main()
  File "update_status.py", line 315, in main
    monitor_dict, uptime_robot_api_key, cachet = parse_config(args.config_file)
  File "update_status.py", line 373, in parse_config
    element_int = int(element)
ValueError: invalid literal for int() with base 10: 'uptimeRobotMonitorID1'
```

**Comment by Baptistecottey** [comment]
Hey,

Same error, using docker image

**Comment by mnucci** [comment]
I am also using a Docker image but it is not the 2.3.13 formal docker release image, it is a 2.4-Dev version that I have created.

I am excited to use this code if I could get it to work so any help would be very much appreciated.

**Comment by MarcHagen** [comment]
Hi! Thanks for reporting, looks like you're missing something in you're config. 
The `UptimeRobotMainApiKey` needs to be in a `[uptimeRobot]` block

So you're config should be ::
```
[uptimeRobot]
UptimeRobotMainApiKey = xxx

[cachet] // Global cachet status API
CachetApiKey = xxx
CachetUrl = http://status.mysite.com

[123123123] // This will update ComponentId 1 on the global Cachet
ComponentId = 1
```

Update:
You need to replace the uptimeRobotMonitorID1 with ids.
To get these ids run `python3 update_status.py --printIds`

Readme quote:

> uptimeRobotMonitorID: This exact "monitor" id set in UptimeRobot. You can find the id's by running python update_status.py config.ini --printIds

**Comment by MarcHagen** [comment]
@mnucci @Baptistecottey Any luck already :)?

**Comment by Mr56k** [comment]
It is a long time with no answers, but maybe it will help:
For getting all the monitor ID's from UptimeRobot, you need to delete all the sections with the [uptimeRobotMonitorIDXX] from the config.ini BEFORE running 
`python update_status.py config.ini --printIds!`
