### ISSUE TITLE
Somehow receiving uptime values above 100%

### ISSUE THREAD

**Issue by brianjking** [Axiacore/cachet-uptime-robot#4]
<img width="755" alt="screenshot8-13-1611 46" src="https://cloud.githubusercontent.com/assets/6786817/17650736/8faee018-621a-11e6-821c-0c95c966497e.png">

<img width="855" alt="screenshot8-14-1612 36" src="https://cloud.githubusercontent.com/assets/6786817/17650771/b9dd2600-621b-11e6-9758-c9f2bdbce1ef.png">
<img width="630" alt="screenshot8-14-1612 35" src="https://cloud.githubusercontent.com/assets/6786817/17650772/b9de098a-621b-11e6-8e69-5a80d01ac45b.png">

**Comment by brianjking** [comment]
@PabloVallejo @felipe3dfx -- I created a new metric and updated my config.ini to reference metric ID 2 instead and it's also getting values above 100%.

Any ideas? Thanks!

**Comment by PabloVallejo** [comment]
@brianjking in order not to get these values you have to set the threshold between metric points to `0`, this will prevent multiple points to get sum up.

![screen shot 2016-08-16 at 10 33 00 am](https://cloud.githubusercontent.com/assets/1751074/17705130/eef4336a-639c-11e6-8043-03f5a1935884.png)

**Comment by brianjking** [comment]
@PabloVallejo Should the `Default Value` in the metric be 0 or 100?

**Comment by PabloVallejo** [comment]
@brianjking it should be 100
