### ISSUE TITLE
Ignore uptimerobot update when manually selected cachet status

### ISSUE THREAD

**Issue by ghost** [Axiacore/cachet-uptime-robot#40]
Is there any way to ignore the update from uptimerobot when we manually select a Cachet status?

For example, if we get a complaint that our API seems to be slower than usual, we would update the status to 'Performance Issues', but after a couple of minutes, uptimerobot will update the status back to 'Operational' because it's only checking for keywords from the /api/ping test.

**Comment by MarcHagen** [comment]
Atm there is no option or way to do that.
