### ISSUE TITLE
Component enabled/disabled

### ISSUE THREAD

**Issue by Tigerpanzer02** [Axiacore/cachet-uptime-robot#41]
After succesfull setup and everything is working I see that I found a bug.

If it updates the status of one monitor the component in cachet will be disabled and so everyone is not seeing the problem.

**Comment by MarcHagen** [comment]
That’s indeed wierd and shouldn’t be the case. Will take a look at it soon.
What version of cachet do you use?

**Comment by Tigerpanzer02** [comment]
I am using the 2.4.0-dev version because that is the only version that I can use on a server that have a php version that is higher than 5

**Comment by MarcHagen** [comment]
Yes i see what you mean, have the same problem when i tested it.
But this is something that should be fixed within CachetHQ.
There is already a issue for it: CachetHQ/Cachet#3288

**Comment by Tigerpanzer02** [comment]
Let us hope that they are fixing this as soon as possible

**Comment by MarcHagen** [comment]
Issue resolved in latest 2.4-dev
