### ISSUE TITLE
Multiple Monitors Support?

### ISSUE THREAD

**Issue by brianjking** [Axiacore/cachet-uptime-robot#5]
Hi,

Is it possible to setup multiple monitors in a single config.ini? 

If not, can I make a config2.ini and setup a separate cron for this?
- 2 Cachet Installs 
- 1 UptimeRobot account/API key
- If using a single config.ini file is supported do I simply add a second entry of the following details from config.ini below the first?

```
[https://url.in.uptime.robot.com]
CachetApiKey = cachet-api-key
CachetUrl = https://status.mycompany.com
MetricId = 1
ComponentId = 1
```
- If this doesn't work would creating a `config2.ini` be the right method?

Thanks again for making this!

**Comment by PabloVallejo** [comment]
Hi @brianjking the library does support updating multiple monitors, you just have to add a block for each cachet metric like this:

```
[https://myfirstcompany.com]
CachetApiKey = cachet-api-key
CachetUrl = https://status.myfirstcompany.com
MetricId = 1
ComponentId = 1

[https://mysecondcompany.com]
CachetApiKey = cachet-api-key
CachetUrl = https://status.mysecondcompany.com
MetricId = 1
ComponentId = 1
```

**Comment by brianjking** [comment]
@PabloVallejo Okay, I've added the 2nd company with it's relevant details in the second block of config.ini.

The first site shows the results data response, the 2nd site doesn't show anything (no response or errors). Should I include the UptimeRobot per block as well?

```
[uptimeRobot]
UptimeRobotMainApiKey = abcd
```

**Comment by camilonova** [comment]
@brianjking you need to have a different .ini file and pass it as an argument to the executable.

**Comment by brianjking** [comment]
@camilonova Okay, I've created a second config.ini file, however, I'm getting strange errors.

```
root@ee:~/cachet-uptime# python3 update_status.py config-duel.ini
Updating monitor duelingdogs.net. URL: https://duelingdogs.net/. ID: 777870577
Traceback (most recent call last):
  File "update_status.py", line 246, in <module>
    MONITOR.update()
  File "update_status.py", line 215, in update
    self.send_data_to_catchet(monitor)
  File "update_status.py", line 191, in send_data_to_catchet
    int(monitor.get('status'))
  File "update_status.py", line 100, in update_component
    response = request.urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

Cachet site URL is http://monitor.duelingdogs.net, btw.

**Comment by camilonova** [comment]
Looking further you should be fine using only one file, since you are using only one UptimeRobot account.

Seems like an error on cachet. Please make sure you are using the correct `MetricId` and `CachetApiKey`.

You should have only one UptimeRobot block and two (or more) cachet blocks.

We are currently using that setup and is working fine for us.

Please check again and let me know.

**Comment by brianjking** [comment]
@camilonova In my `config.ini` I have 4 different sites that are supposed to be monitored, these are across 2 different Cachet sites, and all contained within 1 single UptimeRobot account.

However, when I call the monitor script manually or via cron it seems it's only actually showing data from 2 of 4 sites. No errors are shown.

```
[uptimeRobot]
UptimeRobotMainApiKey = REDACTED

[https://dockdogs.com/]
CachetApiKey = REDACTED
CachetUrl = http://monitor.dockdogs.com/
MetricId = 2
ComponentId = 1

[http://dockdogsevents.com/]
CachetApiKey = REDACTED
CachetUrl = http://monitor.dockdogs.com/
MetricId = 3
ComponentId = 5

[https://duelingdogs.net/]
CachetApiKey = REDACTED
CachetUrl = http://monitor.duelingdogs.net/
MetricId = 1
ComponentId = 1

[https://www.duelingdogsevents.com/]
CachetApiKey = REDACTED
CachetUrl = http://monitor.duelingdogs.net/
MetricId = 2
ComponentId = 2
```

What's strange is it seems to only ever get any data for site 1 & site 3, leaving sites 2 and 4 never showing any uptime percentages (outside of the default 100% configured inside of the Cachet metric.

```
python3 ~/cachet-uptime/update_status.py ~/cachet-uptime/config.ini
Updating monitor dockdogs.com. URL: https://dockdogs.com/. ID: 775915061
Metric created: {'data': {'updated_at': '2016-09-11 12:25:07', 'id': 39116, 'calculated_value': 99.86, 'metric_id': 2, 'created_at': '2016-09-11 12:25:04', 'counter': 1, 'value': 99.86}}
Updating monitor duelingdogs.net. URL: https://duelingdogs.net/. ID: 777870577
Metric created: {'data': {'updated_at': '2016-09-11 12:25:08', 'id': 32812, 'calculated_value': 100, 'metric_id': 1, 'created_at': '2016-09-11 12:25:08', 'counter': 1, 'value': 100}}
```

Any ideas? Suggestions? 

Thanks!

**Comment by brianjking** [comment]
@camilonova @PabloVallejo Updated to latest update_status.py file as seen in https://github.com/Axiacore/cachet-uptime-robot/commit/66850bb5fc4989f03282de66ff6e33f2bc0616aa, however, I'm still seeing the same results as I reported [here](https://github.com/Axiacore/cachet-uptime-robot/issues/5#issuecomment-246192209).

Any ideas? Thanks!

```
root@ee:~/cachet-uptime# git pull
remote: Counting objects: 3, done.
remote: Total 3 (delta 2), reused 2 (delta 2), pack-reused 1
Unpacking objects: 100% (3/3), done.
From https://github.com/Axiacore/cachet-uptime-robot
   d8d661b..66850bb  master     -> origin/master
Updating d8d661b..66850bb
Fast-forward
 update_status.py | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
root@ee:~/cachet-uptime# python3 update_status.py config.ini
Updating monitor dockdogs.com. URL: https://dockdogs.com/. ID: 775915061
Metric created: {'data': {'counter': 1, 'value': 99.86, 'metric_id': 2, 'calculated_value': 99.86, 'created_at': '2016-09-15 09:47:02', 'updated_at': '2016-09-15 09:47:04', 'id': 44523}}
Updating monitor duelingdogs.net. URL: https://duelingdogs.net/. ID: 777870577
Metric created: {'data': {'counter': 1, 'value': 100, 'metric_id': 1, 'calculated_value': 100, 'created_at': '2016-09-15 09:47:04', 'updated_at': '2016-09-15 09:47:04', 'id': 38217}}
```

**Comment by camilonova** [comment]
@brianjking Hard to guess, maybe check again your API Key or try to add print statements to check if there is something wrong.

**Comment by brianjking** [comment]
There are two Cachet API keys, the two sites the site reports metric data for are from both Cachet installs.

I just temporarily removed https://duelingdogs.net (one of the two sites) from my config.ini and executed the script and it now only reports data for 1 of the sites, still ignoring 2 of 3 sites.

**Comment by brianjking** [comment]
I figured it out, nothing was wrong with the script. Closing now, will explain in the morning!

**Comment by TheBrockEllis** [comment]
@brianjking Any chance you could update us on what was wrong? I read this entire thread and now I'm on pins and needles!
