### ISSUE TITLE
Cachet Not Updated

### ISSUE THREAD

**Issue by thetechgy** [Axiacore/cachet-uptime-robot#7]
We have a CentOS 7 x64 VM running on AWS that's running our Cachet instance. On the same VM I did a git clone of the current version of the cachet-uptime-robot. I created a single monitor for https://helpdesk.ritzmanrx.com in config.ini and added our API keys. The Cachet page doesn't update after running the command manually. Any suggestions? Uptime Robot shows the helpdesk page up with a response of 200 on their web interface

![image](https://cloud.githubusercontent.com/assets/17523918/18373563/430f5d52-7613-11e6-80ee-8dceb6e64f82.png)

**Comment by PabloVallejo** [comment]
Please show us your config.ini

**Comment by thetechgy** [comment]
Config.ini contents shown below. I'm a little unclear on where the MetricId or ComponentId are found. I don't currently have any metrics in Cachet

[centos@status cachet-uptime-robot]$ cat config.ini
[uptimeRobot]
UptimeRobotMainApiKey = redacted

[https://helpdesk.ritzmanrx.com]
CachetApiKey = redacted
CachetUrl = http://status.ritzmanrx.com
MetricId = 1
ComponentId = 1

**Comment by camilonova** [comment]
You sure you are using the latest version?

Maybe is related with #6
