### ISSUE TITLE
Invalid CachetAPIKey Issue

### ISSUE THREAD

**Issue by nick592prouty** [Axiacore/cachet-uptime-robot#8]
Hi,

I am getting some issues while configuring cachet-uptime-robot, below is the error:

> Traceback (most recent call last):
>   File "update_status.py", line 236, in <module>
>     'cachet_api_key': CONFIG[element]['CachetApiKey'],
>   File "/usr/lib/python3.4/configparser.py", line 1203, in **getitem**
>     raise KeyError(key)
> KeyError: 'CachetApiKey'

Below is my config.ini file:

```
[plex5]
UptimeRobotMainApiKey = 'uxxxxxx-xxxxxxxxxxxxxxxxxxxxx'

[https://uptimerobot.com/dashboard.php#xxxxxxxx]
CachetApiKey = 'PHB2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxKC1o='
CachetUrl = 'http://status.xxxxxxxx.com'
MetricId = 2
ComponentId = 1
```

Any idea what could be causing the issue, do I need "base64:" as a prefix for the CachetApiKey  ? Does the CachetApiKey need to be in quotes ?

**Comment by nick592prouty** [comment]
I fixed that issue, I am getting a new error now:

> root@lamp-xxxxxxx-01:/var/cachet_robot# python3 update_status.py config.ini
> Updating monitor website. URL: https://nixxxxxo.com. ID: 7xxxxx39
> Traceback (most recent call last):
>   File "update_status.py", line 246, in <module>
>     MONITOR.update()
>   File "update_status.py", line 215, in update
>     self.send_data_to_catchet(monitor)
>   File "update_status.py", line 191, in send_data_to_catchet
>     int(monitor.get('status'))
>   File "update_status.py", line 100, in update_component
>     response = request.urlopen(req)
>   File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.4/urllib/request.py", line 469, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.4/urllib/request.py", line 501, in error
>     result = self._call_chain(_args)
>   File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
>     result = func(_args)
>   File "/usr/lib/python3.4/urllib/request.py", line 663, in http_error_302
>     new = self.redirect_request(req, fp, code, msg, headers, newurl)
>   File "/usr/lib/python3.4/urllib/request.py", line 610, in redirect_request
>     raise HTTPError(req.full_url, code, msg, headers, fp)
> urllib.error.HTTPError: HTTP Error 301: Moved Permanently

Config File is : 

[uptimeRobot]
UptimeRobotMainApiKey = u27xxxx8-fe97xxxxxxxxxxxxxxx0dxxx72

[https://nicxxxxno.com]
CachetApiKey = PHB2lSIwxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8KC1o=
CachetUrl = http://staxx.xxxxxxs.com
MetricId = 2
ComponentId = 1

**Comment by nick592prouty** [comment]
I started printing out some variables to determine the issue, still getting a 301 error. I tried removing the trailing "/" from the URL but that caused more issues. I am getting valid data from uptime robot, it's failing when it calls "response = request.urlopen(req)" on line [100](https://github.com/Axiacore/cachet-uptime-robot/blob/master/update_status.py#L100)

{'https://api.uptimerobot.com/getMonitors?apiKey=u277028-xxxxxxxxxxxxxxxxxxxxx3672&noJsonCallback=1&format=json&responseTimes=1&logs=0&customUptimeRatio=30'}
Updating monitor website. URL: https://nicxxxxxo.com. ID: 7xxxxxx9
here
{None}
73
86
{1}
{'http://status.nicxxxxxx.com/api/v1/components/7/'}
{b'status=1'}
{'X-Cachet-Token': 'PHB2lxxxxxxxxxxxxxxxxxxxxxxxxxxxxKC1o='}
106
Traceback (most recent call last):
  File "update_status.py", line 262, in <module>
    MONITOR.update()
  File "update_status.py", line 231, in update
    self.send_data_to_catchet(monitor)
  File "update_status.py", line 207, in send_data_to_catchet
    int(monitor.get('status'))
  File "update_status.py", line 111, in update_component
    response = request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 501, in error
    result = self._call_chain(_args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.4/urllib/request.py", line 663, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib/python3.4/urllib/request.py", line 610, in redirect_request
    raise HTTPError(req.full_url, code, msg, headers, fp)
urllib.error.HTTPError: HTTP Error 301: Moved Permanently

**Comment by nick592prouty** [comment]
This Can be closed, I have figured out the issues. A few things I would like to note for people trying to set this up:

1) Your components/metrics must be created in cachet first
2)When you edit a component in cachet the URL will have the componentID the config file ask for in it. e.g. "http://status.nixxxxxxs.com/dashboard/components/**1**/edit"  , same with the metrics "http://status.nickflixs.com/dashboard/metrics/**2**/edit" - you use these ids to mach the component you created in cachet to the config file
3)The links in the [config ](https://github.com/Axiacore/cachet-uptime-robot/blob/master/config.ini#L4)file must match exactly what is shown in the "URL (or IP) *" field in UptimeRobot
4) The cachet API Key is found on the cachet page when you click on the power icon in the top left, it's NOT the "APP_KEY=SomeRandomString" in the .env file in the cachet web folder 
5)The settings I chose for metrics are the following : "Calculation of metrics":"Average" ,"Default View":"Last 12 Hours","Default Value":0,"Decimal Places":0, "How many minutes of threshold between metric points?":0
6) Below is my working config file with multiple sites being monitored : 

```
[uptimeRobot]
UptimeRobotMainApiKey = uxxxxx8-fxxxxxxxxxxxxxxxxxx2

[https://nixxxxxxo.com]
CachetApiKey = hxxxxxxxxxxxxxxxxxk
CachetUrl = http://staxxxxxxxxxxxxs.com
MetricId = 7
ComponentId = 7

[https://robxxxxxxxxxxxxxxxxxxxxxdex.html]
CachetApiKey = hxxxxxxxxxxxxxxxxxk
CachetUrl = http://stxxxxxxxxxxxxs.com
MetricId = 1
ComponentId = 4

[https://robbush.com:32769/web/index.html]
CachetApiKey = hxxxxxxxxxxxxxxxxxk
CachetUrl = http://stxxxxxxxxxxxxs.com
MetricId = 6
ComponentId = 5

[https://nixxxxxxxxxxxxxxxxxxxx.html]
CachetApiKey = hxxxxxxxxxxxxxxxxxk
CachetUrl = http://stxxxxxxxxxxxxs.com
MetricId = 3
ComponentId = 1

[https://nicxxxxxxxxxxxxxxxxxxxxxxex.html]
CachetApiKey = hxxxxxxxxxxxxxxxxxk
CachetUrl = http://stxxxxxxxxxxxxs.com
MetricId = 4
ComponentId = 2

[https://nicxxxxxxxxxxxxxxxxxxxxxxxex.html]
CachetApiKey = hxxxxxxxxxxxxxxxxxk
CachetUrl = http://stxxxxxxxxxxxxs.com
MetricId = 2
ComponentId = 20

[https://ownxxxxxxxxxxxxxxxxxxom]
CachetApiKey = hxxxxxxxxxxxxxxxxxk
CachetUrl = http://stxxxxxxxxxxxxs.com
MetricId = 8
ComponentId = 21

[https://nicxxxxxxxxxxxxxxxxxxxdex.html]
CachetApiKey = hxxxxxxxxxxxxxxxxxk
CachetUrl = http://stxxxxxxxxxxxxs.com
MetricId = 5
ComponentId = 3
```

**Comment by PabloVallejo** [comment]
Thanks @nick592prouty !

**Comment by RochaNeto** [comment]
Hello my friends.

I can do the update of the metric, but my component only displays "operational" even the monitoring accusing being down.

What am I doing wrong?

**Comment by RochaNeto** [comment]
@camilonova @nick592prouty

**Comment by camilonova** [comment]
I'm not sure, check your cachet instance. I guess this is not meant to mark your site as non operational, but will be useful if you want to work on that.

PRs are welcome.

**Comment by RochaNeto** [comment]
You believe he doesn't have this functionality? The purpose is to display the metric, correct?

I guess I got it wrong then. Thank you very much.
